dist: xenial
language: python
os: linux
python:
  - '3.5'
  - '3.6'
  - '3.7'
before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin python-gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
install:
  - pip install GDAL==`gdal-config --version`
  - pip install -r requirements.txt
script:
  - py.test tests/ --pep8 lmpy -v --cov lmpy --cov-report term-missing
after_success:
  - coveralls
jobs:
  include:
  - stage: deploy
    python: '3.7'
    before_install:
    - sudo add-apt-repository --yes ppa:ubuntugis/ppa
    - sudo apt-get --quiet update
    - sudo apt-get install --yes libgdal-dev gdal-bin python-gdal
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
    install:
    - pip install GDAL==`gdal-config --version`
    - pip install -r requirements.txt
    before_deploy:
    - python setup.py sdist bdist_wheel
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: IL/Lr0dFvey+nWipt4dtfp9i93wEOxX9G6U+hnFvPuMxi441TVJ4fCw4dccyEfoqsYxPn9Hhqih2h2LsomZqcBgG0Qfph+Z8wjxF63icfhFYcI6fXmZ0YAPqaW3hKuooLc1dkebfOVilTKbdjNY5blwN3+XgxVig26Ic8fSjOhDg+ZKbTa+AwshxhmoV3oy7dLtsq+xFH2L1pRpECLFM7BiaSw4up6so52zsDSwIInzck5w+QGh8NMr6uKiZ1KwZrzW42uCGiV164NwENsonY7ssCe/vZe9Cl39Rrm91g1N0XMx11VvLD4Z+tRqC1mySWD9MpHX+VNIhWSQ1Xc52JxlPNCjLOKrGX3louVldChrkOxKbn//JUFuqSClJ5pYAB256lDHjP6CYeNPJhOSfe0WHhrgC5TFZIjzAEZX5tnr+dkK5mNF5U2WKEv6JHkdcggLd/hsXdeIZ1SbCmYvM5LwyrHs/V+C74XF5lbF0gM/Hx6SzVYHrcknahaFepJ5r1Pnkk7zZFv2/OGxhYVWsFjyek9tCU43CnfXzT3DohQ1zhAq4LchOssNI9l34SE4ibbIdF3p1nTlksfBy0ENqYd05kr+/zzZL5bnWU0Z0zaUAFyMf/rG3mdwImDkooWatkcSa7afQWUw/BM0vxVrtRkJivFXVu4n4JNJISbbLd94=
      file_glob: true
      file: dist/*
      on:
        tags: true
        repo: cjgrady/lmpy
